version: "3.8"
services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: uber_postgres
    restart: always
    environment:
      POSTGRES_DB: uberdb
      POSTGRES_USER: uberuser
      POSTGRES_PASSWORD: uberpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: uber_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: uber_kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka

  redis:
    image: redis:7-alpine
    container_name: uber_redis
    ports:
      - "6379:6379"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: uber_kafka_ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8081:8080"

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: uber_kafka_exporter
    depends_on:
      - kafka
    command: ["--kafka.server=kafka:9092"]
    ports:
      - "9308:9308"

  prometheus:
    image: prom/prometheus:latest
    container_name: uber_prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - kafka-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: uber_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
  kafka_data:
