{
 "title": "Orchestrator Service",
 "tags": [
  "service",
  "orchestrator"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Orchestrator - Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator-service\"}[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Orchestrator - 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator-service\",status=~\"5..\"}[1m]))",
     "legendFormat": "5xx/s"
    }
   ]
  },
  {
   "title": "Orchestrator - p95 Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{application=\"orchestrator-service\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Orchestrator - 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator-service\",status=~\"4..\"}[1m]))",
     "legendFormat": "4xx/s"
    }
   ]
  }
 ]
}