spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uberdb
    username: uberuser
    password: uberpass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
  sql:
    init:
      mode: always

server:
  port: 8080
