{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    release: prometheus
    {{- toYaml .Values.monitoring.serviceMonitor.extraLabels | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.serviceMonitor.namespace | default .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "notification.name" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
{{- end }}
