apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels: {{- include "gateway.labels" . | nindent 4 }}
{{- if not .Values.rollout.enabled }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if or .Values.secrets.create .Values.secrets.name }}
          envFrom:
            - secretRef:
                name: {{- if .Values.secrets.name -}}{{ .Values.secrets.name }}{{- else -}}{{ include "gateway.fullname" . }}-secret{{- end }}
          {{- end }}
          env:
            - name: JWT_ENABLED
              value: "{{ .Values.env.JWT_ENABLED }}"
            {{- if not (or .Values.secrets.create .Values.secrets.name) }}
            - name: JWK_SET_URI
              value: "{{ .Values.env.JWK_SET_URI }}"
            {{- end }}
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
            {{- if not (or .Values.secrets.create .Values.secrets.name) }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.secrets.name -}}{{ .Values.secrets.name }}{{- else -}}{{ include "gateway.fullname" . }}-secret{{- end }}
                  key: REDIS_PASSWORD
            {{- end }}
            - name: RATE_LIMIT_REPLENISH
              value: "{{ .Values.env.RATE_LIMIT_REPLENISH }}"
            - name: RATE_LIMIT_BURST
              value: "{{ .Values.env.RATE_LIMIT_BURST }}"
            - name: RATE_LIMIT_BOOKING_REPLENISH
              value: "{{ .Values.env.RATE_LIMIT_BOOKING_REPLENISH }}"
            - name: RATE_LIMIT_BOOKING_BURST
              value: "{{ .Values.env.RATE_LIMIT_BOOKING_BURST }}"
            - name: RATE_LIMIT_ORCH_REPLENISH
              value: "{{ .Values.env.RATE_LIMIT_ORCH_REPLENISH }}"
            - name: RATE_LIMIT_ORCH_BURST
              value: "{{ .Values.env.RATE_LIMIT_ORCH_BURST }}"
            - name: RATE_LIMIT_NOTIF_REPLENISH
              value: "{{ .Values.env.RATE_LIMIT_NOTIF_REPLENISH }}"
            - name: RATE_LIMIT_NOTIF_BURST
              value: "{{ .Values.env.RATE_LIMIT_NOTIF_BURST }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
{{- end }}
