apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "booking.fullname" . }}
  labels: {{- include "booking.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "booking.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "booking.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ include "booking.serviceAccountName" . }}
      containers:
        - name: booking
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if or .Values.secrets.create .Values.secrets.name }}
          envFrom:
            - secretRef:
                name: {{ include "booking.awsSecretName" . }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.SPRING_DATASOURCE_URL }}"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.SPRING_KAFKA_BOOTSTRAP_SERVERS }}"
            - name: ANALYTICS_EXPORT_ENABLED
              value: "{{ .Values.env.ANALYTICS_EXPORT_ENABLED }}"
            - name: ANALYTICS_S3_BUCKET
              value: "{{ .Values.env.ANALYTICS_S3_BUCKET }}"
            - name: ANALYTICS_S3_PREFIX
              value: "{{ .Values.env.ANALYTICS_S3_PREFIX }}"
            - name: AWS_REGION
              value: "{{ .Values.env.AWS_REGION }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.env.AWS_ACCESS_KEY_ID }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.env.AWS_SECRET_ACCESS_KEY }}"
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
