{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "booking.awsSecretName" . }}
  labels: {{- include "booking.labels" . | nindent 4 }}
  annotations: {}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.data.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.data.AWS_SECRET_ACCESS_KEY | quote }}
{{- end }}
