{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "booking.serviceAccountName" . }}
  labels: {{- include "booking.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.iam.useIRSA }}
    eks.amazonaws.com/role-arn: {{ .Values.iam.roleArn | quote }}
    {{- end }}
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}
